export enum OrderStatusApiEnum {
  SUBMITTED = 'SUBMITTED',
  APPROVAL = 'APPROVAL',
  COMPLETED = 'COMPLETED',
  FULFILL = 'FULFILL',
  PACKAGING = 'PACKAGING',
  SOON = 'SOON',
  PARTSHIPPED = 'PARTSHIPPED',
  SHIPPED = 'SHIPPED',
}
