export enum ValueEnum {
  BOOLEAN = 'BOOLEAN',
  BOOL = 'BOOL',
  INTEGER = 'INTEGER',
  DATE = 'DATE',
  LOCATION = 'LOCATION',
  PROVINCE = 'PROVINCE',
  CITY = 'CITY',
  TYPE_REGISTRATION = 'TYPE_REGISTRATION',
}
