export enum TableFieldTypesEnum {
  TEXT = 'text',
  TEXT_WITH_ACTION = 'text-with-ation',
  TEXT_LABEL = 'text-label',
  TEXT_ARRAY = 'text-array',
  DATE = 'date',
  DATE_SHORT = 'date-short',
  DATE_DUE = 'date-due',
  SIZE = 'size',
  INNER_HTML = 'inner-html',
  DYNAMIC_TEXT = 'dynamic text',
  PRICE = 'price',
  PRICE_DUE = 'price-due',
  PROGRESS_STATUS = 'progress status',
  PAYMENT_METHOD = 'payment method',
  ADDRESS = 'address',
  PRODUCTS = 'products',
  TOGGLE = 'toggle',
  ACTION = 'action',
  PROFILE = 'profile',
  CONTACTS = 'contacts',
  LINK = 'link',
  EXPAND = 'expand',
}
