import { SubscriptionStatusApiEnum } from '@features/account/enums';
import { BillingInfoApiModel, CustomerApiModel } from '@features/account/models/api';
import { AddressAPIModel } from '@features/addresses/models/api';
import { ProductApiModel } from '@shared/models/product';

export interface SubscriptionApiModel {
  subscriptionId: string;
  orderId: number;
  subscriptionConfigId: string;
  $subscriptionConfigId: string;
  subscriptionType: string;
  $subscriptionType: string;
  subscriptionStatus: SubscriptionStatusApiEnum;
  $subscriptionStatus: string;
  createdDate: string;
  startDate: string;
  currentCycleStart: string;
  currentCycleEnd: string;
  endDate: string;
  createdBy: string;
  $createdBy: string;
  description: string;
  salesTeam: string;
  product?: ProductApiModel[];
  recurrence: string;
  customerInfo: CustomerApiModel;
  billingInfo: BillingInfoApiModel;
  serviceAddress: AddressAPIModel;
  lastUpdated: string;
  updatedBy: string;
  $updatedBy: string;
  chargeInfo?: any;
  extension?: any;
  cancelAfter: number;
  notificationId?: any;
  attentionRequired: boolean;
  pricingInfo?: any[];
  progressHistory?: any[];
  relatedItem?: any[];
}
