export enum PaymentMethodEnum {
  BCA = 'BERSAMA_BCA',
  BNI = 'BERSAMA_BNI',
  BRI = 'BERSAMA_BRI',
  CREDIT_CARD = 'BERSAMA_CC',
  MANDIRI = 'BERSAMA_MANDIRI',
  OVO = 'BERSAMA_OVO',
  BERSAMA = 'BERSAMA_VA',
  CASH = 'CASH',
  GOPAY = 'BERSAMA_GOPAY',
}
