export enum RouteQueryParamsEnum {
  PRODUCT_CODE = 'productCode',
  PRODUCT_CATEGORY_ID = 'categoryId',
  ORDER = 'order',
  ORDER_PAYMENT = 'orderPayment',
  APPROVAL_TYPE = 'approvalType',
  LOCATION_ID = 'locationId',
  PAYMENT_TOKEN = 'paymentToken',
  SALES_TEAM = 'salesTeam',
  DELIVERY_CONFIRMATION_CODE = 'confirmationCode',
  EMPLOYEE_PAYMENT = 'employeePayment',
  ACP_CODE = 'ACP',
  ZEALS_CODE = 'encrypted_code',
  JWT = 'jwt',
  AH_JWT = '$jwt',
  ASSOCIATION_TYPE = 'associationType',
  ACCOUNT_ID = 'accountId',
  CONTEXT_ID = 'contextId',
  NAME = 'name',
  LANG = 'lang',
}
