import { BillingInfoApiModel, CustomerApiModel } from '@features/account/models/api';
import { ProductApiModel } from '@shared/models/product';

import { OrderCartTotalApiModel } from './order-cart-total-api.model';
import { OrderPaymentInfoApiModel } from './order-payment-info-api.model';
import { OrderProgressApiModel } from './order-progress-api.model';
import { OrderShippingAddressApiModel } from './order-shipping-address-api.model';
import { OrderShippingInfoApiModel } from './order-shipping-info-api.model';

export interface OrderApiModel {
  customerInfo: CustomerApiModel;
  orderProgress?: OrderProgressApiModel[];
  product?: ProductApiModel[];
  shipToAddress?: OrderShippingAddressApiModel[];
  billingInfo: BillingInfoApiModel;
  paymentInfo: OrderPaymentInfoApiModel;
  shippingInfo: OrderShippingInfoApiModel[];
  cartTotal: OrderCartTotalApiModel[];
  lastPricedDate: string;
  repriceOnOpen: boolean;
  locked: boolean;
  currency: string;
  type: string;
  orderId: string;
  processId: string;
  hasTask: boolean;
  orderType: string;
  $orderType: string;
  orderState: string;
  $orderState: string;
  orderStatus: string;
  $orderStatus: string;
  orderSource: string;
  $orderSource: string;
  createdDate: string;
  submittedDate: string;
  createdBy: string;
  $createdBy: string;
  salesChannel: string;
  $salesChannel: string;
  salesTeam: string;
  lastUpdated: string;
  orderPriority: number;
  progressHistory?: any[];
  extension?: any[];
  orderTag?: any[];
  relatedItem?: any[];
  charge?: any[];
  grandTotal: any;
  requiredItem?: any[];
  commitmentTotal?: any;
  coupon?: any[];
  __metadata: any;
}
