export const CURRENCY_PIPE_FORMAT = '1.0-0';
export const NUMBER_PIPE_FORMAT = '1.0-2';
export const DECIMAL_NUMBER_PIPE_FORMAT = '2.2';
export const DATE_FORMAT = 'MM/dd/YYYY';
export const LONG_DATE_FORMAT = 'MMM d, y';
export const TIME_FORMAT = 'HH:mm';
export const YEAR_FORMAT = 'YYYY';
export const DATE_TABLE_FORMAT = 'MMM d, y H:mm';
export const SHORT_DATE_TIME_FORMAT = 'MMM d, H:mm';

export const PIPE_FORMATS = {
  CURRENCY: CURRENCY_PIPE_FORMAT,
  NUMBER: NUMBER_PIPE_FORMAT,
  DECIMAL: DECIMAL_NUMBER_PIPE_FORMAT,
  DATE: DATE_FORMAT,
  TIME: TIME_FORMAT,
  DATE_TIME: DATE_TABLE_FORMAT,
  LONG_DATE: LONG_DATE_FORMAT,
  YEAR: YEAR_FORMAT,
  SHORT_DATE_TIME: SHORT_DATE_TIME_FORMAT,
};
